
# ----- Narrow Left Stereocam (Rectified) -----
narrow_left_rect:
  cb_detector_config:  /narrow_stereo/left/cb_detector_config
  led_detector_config: /narrow_stereo/left/led_detector
  settler_config:      /narrow_stereo/left/monocam_settler_config

  configs:
    cb_7x6:
      settler:
        tolerance: 2.00
        ignore_failures: True
        max_step: 1.0
        cache_size: 100
      cb_detector:
        active: True
        num_x: 7
        num_y: 6
        width_scaling: 1
        height_scaling: 1
        subpixel_window: 4
        subpixel_zero_zone: 1
      led_detector:
        active: False
    small_cb_4x5:
      settler:
        tolerance: 2.00
        ignore_failures: True
        max_step: 1.0
        cache_size: 100
      cb_detector:
        active: True
        num_x: 4
        num_y: 5
        width_scaling: 1
        height_scaling: 1
        subpixel_window: 4
        subpixel_zero_zone: 1
      led_detector:
        active: False

# ----- Narrow Right Stereocam (Rectified)-----
narrow_right_rect:
  cb_detector_config:  /narrow_stereo/right/cb_detector_config
  led_detector_config: /narrow_stereo/right/led_detector
  settler_config:      /narrow_stereo/right/monocam_settler_config

  configs:
    cb_7x6:
      settler:
        tolerance: 2.00
        ignore_failures: True
        max_step: 1.0
        cache_size: 100
      cb_detector:
        active: True
        num_x: 7
        num_y: 6
        width_scaling: 1
        height_scaling: 1
        subpixel_window: 4
        subpixel_zero_zone: 1
      led_detector:
        active: False
    small_cb_4x5:
      settler:
        tolerance: 2.00
        ignore_failures: True
        max_step: 1.0
        cache_size: 100
      cb_detector:
        active: True
        num_x: 4
        num_y: 5
        width_scaling: 1
        height_scaling: 1
        subpixel_window: 4
        subpixel_zero_zone: 1
      led_detector:
        active: False


# ----- Wide Left Stereocam (Rectified)-----
wide_left_rect:
  cb_detector_config:  /wide_stereo/left/cb_detector_config
  led_detector_config: /wide_stereo/left/led_detector
  settler_config:      /wide_stereo/left/monocam_settler_config

  configs:
    cb_7x6:
      settler:
        tolerance: 2.00
        ignore_failures: True
        max_step: 1.0
        cache_size: 100
      cb_detector:
        active: True
        num_x: 7
        num_y: 6
        width_scaling: 2
        height_scaling: 2
        subpixel_window: 4
        subpixel_zero_zone: 1
      led_detector:
        active: False
    small_cb_4x5:
      settler:
        tolerance: 2.00
        ignore_failures: True
        max_step: 1.0
        cache_size: 100
      cb_detector:
        active: True
        num_x: 4
        num_y: 5
        width_scaling: 1
        height_scaling: 1
        subpixel_window: 4
        subpixel_zero_zone: 1
      led_detector:
        active: False

# ----- Wide Right Stereocam (Rectified)-----
wide_right_rect:
  cb_detector_config:  /wide_stereo/right/cb_detector_config
  led_detector_config: /wide_stereo/right/led_detector
  settler_config:      /wide_stereo/right/monocam_settler_config

  configs:
    cb_7x6:
      settler:
        tolerance: 2.00
        ignore_failures: True
        max_step: 1.0
        cache_size: 100
      cb_detector:
        active: True
        num_x: 7
        num_y: 6
        width_scaling: 2
        height_scaling: 2
        subpixel_window: 4
        subpixel_zero_zone: 1
      led_detector:
        active: False
    small_cb_4x5:
      settler:
        tolerance: 2.00
        ignore_failures: True
        max_step: 1.0
        cache_size: 100
      cb_detector:
        active: True
        num_x: 4
        num_y: 5
        width_scaling: 1
        height_scaling: 1
        subpixel_window: 4
        subpixel_zero_zone: 1
      led_detector:
        active: False

# ----- Forearm Camera Left (Rectified)-----
forearm_left_rect:
  cb_detector_config:  /l_forearm_cam/cb_detector_config
  led_detector_config: /l_forearm_cam/led_detector
  settler_config:      /l_forearm_cam/monocam_settler_config

  configs:
    cb_7x6:
      settler:
        tolerance: 2.00
        ignore_failures: True
        max_step: 1.0
        cache_size: 100
      cb_detector:
        active: True
        num_x: 7
        num_y: 6
        width_scaling: 2
        height_scaling: 2
        subpixel_window: 4
        subpixel_zero_zone: 1
      led_detector:
        active: False
    small_cb_4x5:
      settler:
        tolerance: 2.00
        ignore_failures: True
        max_step: 1.0
        cache_size: 100
      cb_detector:
        active: True
        num_x: 4
        num_y: 5
        width_scaling: 1
        height_scaling: 1
        subpixel_window: 4
        subpixel_zero_zone: 1
      led_detector:
        active: False

# ----- Forearm Camera Right (Rectified)-----
forearm_right_rect:
  cb_detector_config:  /r_forearm_cam/cb_detector_config
  led_detector_config: /r_forearm_cam/led_detector
  settler_config:      /r_forearm_cam/monocam_settler_config

  configs:
    cb_7x6:
      settler:
        tolerance: 2.00
        ignore_failures: True
        max_step: 1.0
        cache_size: 100
      cb_detector:
        active: True
        num_x: 7
        num_y: 6
        width_scaling: 2
        height_scaling: 2
        subpixel_window: 4
        subpixel_zero_zone: 1
      led_detector:
        active: False
    small_cb_4x5:
      settler:
        tolerance: 2.00
        ignore_failures: True
        max_step: 1.0
        cache_size: 100
      cb_detector:
        active: True
        num_x: 4
        num_y: 5
        width_scaling: 1
        height_scaling: 1
        subpixel_window: 4
        subpixel_zero_zone: 1
      led_detector:
        active: False

# ----- Prosilica (Rectified) -----
prosilica_rect:
  cb_detector_config:  /prosilica/cb_detector_config
  led_detector_config: /prosilica/led_detector
  settler_config:      /prosilica/monocam_settler_config

  configs:
    cb_7x6:
      settler:
        tolerance: 2.00
        ignore_failures: True
        max_step: 3.0
        cache_size: 100
      cb_detector:
        active: True
        num_x: 7
        num_y: 6
        width_scaling: 0.25
        height_scaling: 0.25
        subpixel_window: 4
        subpixel_zero_zone: 1
      led_detector:
        active: False
    small_cb_4x5:
      settler:
        tolerance: 2.00
        ignore_failures: True
        max_step: 3.0
        cache_size: 100
      cb_detector:
        active: True
        num_x: 4
        num_y: 5
        width_scaling: 0.25
        height_scaling: 0.25
        subpixel_window: 4
        subpixel_zero_zone: 1
      led_detector:
        active: False
